name = "web5-claims-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-06-16"

[vars]
WORKERS_RS_VERSION = "0.0.9"
GITHUB_REDIRECT_URL = "https://api.web5.claims/github/callback"
GOOGLE_REDIRECT_URL = "https://api.web5.claims/google/callback"
AZURE_REDIRECT_URL = "https://api.web5.claims/azure/callback"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
